---
title: "CMAJ Analytical and results script: Psychological distress during COVID-19 in Canadian youth with and without chronic health conditions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(here)
library(psych)
library(english)
library(stringr)
library(tableone)
library(kableExtra)
library(scales)
library(ggridges)
library(plotly)
library(patchwork)
library(haven)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(table1)
library(rstatix)
library(car)
library(multcomp)
library(effects)
library(pastecs)
library(rcompanion)
```

```{r data, echo=FALSE, message=FALSE, warning=FALSE}
# Read in the clean csv file
leger <- read_csv("data/cmaj_analyses_jan2022.csv")

# set seed for all analyses and wrangling
set.seed(1)
```

## RESULTS
### Sample

```{r echo=FALSE, warning=FALSE}
table_data <- leger %>%
  dplyr::select(age_yrs, sex, edu, hoinc, province_full, chronic_descriptive, chronic_dummy, chronic_multi, any_m_health, distress_sum, vaccine) %>%
  mutate(chronic_dummy = factor(chronic_dummy,
                                levels = c(0:1),
                                labels = c("Healthy", "Chronic Health Condition")),
         chronic_multi = factor(chronic_multi, 
                                levels = c(0:1),
                                labels = c("No", "Yes")),
         any_m_health = factor(any_m_health,
                               levels = c(0:1),
                               labels = c("No", "Yes")))

label(table_data$sex) <- "Sex"
label(table_data$age_yrs) <- "Age"
label(table_data$edu) <- "Education"
label(table_data$province_full) <- "Province"
label(table_data$hoinc) <- "Income"
label(table_data$chronic_descriptive) <- "Chronic illness"
label(table_data$chronic_multi) <- "Multimorbidity"
label(table_data$any_m_health) <- "Diagnosis of mental health disorder"
label(table_data$distress_sum) <- "COVID-19 distress"
label(table_data$vaccine) <- "Received COVID-19 vaccine?"

units(table_data$age_yrs) <- "years"

table1(~ age_yrs + sex + edu + hoinc + province_full + chronic_descriptive + chronic_multi + any_m_health + distress_sum + vaccine | chronic_dummy,
       data = table_data)

```

# FIGURE
```{r echo=FALSE, fig.width=13, fig.height=16}
leger %>%
  group_by(wave, chronic_dummy) %>%
  shapiro_test(distress_sum)

label <- c("0" = "No chronic health condition", "1" = "Chronic health")
label_wave <- c("2" = "Round 2",
                "3" = "Round 3",
                "4" = "Round 4",
                "5" = "Round 5",
                "6" = "Round 6",
                "7" = "Round 7",
                "8" = "Round 8")

A <- leger %>%
  dplyr::select(wave, chronic_dummy, impacvd_sq001) %>%
  group_by(wave, chronic_dummy, impacvd_sq001) %>%
  drop_na() %>%
  count() %>%
  ungroup(impacvd_sq001) %>%
  mutate(sum = sum(n),
         prop = n/sum*100) %>%
  ggplot(aes(x = impacvd_sq001, y = prop)) +
  geom_col(aes(fill = factor(chronic_dummy)),
               position = 'dodge') +
  facet_grid(~ wave,
             labeller = labeller(wave = label_wave)) +
  theme_bw() +
  scale_fill_discrete(breaks = c(0, 1),
                     labels = c("No", "Yes")) +
  scale_x_continuous(breaks = c(0, 1, 2, 3),
                     labels = c("None", "Little", "Some", "Great extent")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "COVID-19 anxiety", x = "Response", y = "Prooportion (%)", fill = "Chronic condition")
 
B <- leger %>%
  dplyr::select(wave, chronic_dummy, impacvd_sq002) %>%
  group_by(wave, chronic_dummy, impacvd_sq002) %>%
  drop_na() %>%
  count() %>%
  ungroup(impacvd_sq002) %>%
  mutate(sum = sum(n),
         prop = n/sum*100) %>%
  ggplot(aes(x = impacvd_sq002, y = prop)) +
  geom_col(aes(fill = factor(chronic_dummy)),
               position = 'dodge') +
  facet_grid(~ wave,
             labeller = labeller(wave = label_wave)) +
  theme_bw() +
  scale_fill_discrete(breaks = c(0, 1),
                     labels = c("No", "Yes")) +
  scale_x_continuous(breaks = c(0, 1, 2, 3),
                       labels = c("None", "Little", "Some", "Great extent")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "COVID-19 depression", x = "Response", y = "Prooportion (%)", fill = "Chronic condition")

C <- leger %>%
  dplyr::select(wave, chronic_dummy, impacvd_sq003) %>%
  group_by(wave, chronic_dummy, impacvd_sq003) %>%
  drop_na() %>%
  count() %>%
  ungroup(impacvd_sq003) %>%
  mutate(sum = sum(n),
         prop = n/sum*100) %>%
  ggplot(aes(x = impacvd_sq003, y = prop)) +
  geom_col(aes(fill = factor(chronic_dummy)),
               position = 'dodge') +
  facet_grid(~ wave,
             labeller = labeller(wave = label_wave)) +
  theme_bw() +
  scale_fill_discrete(breaks = c(0, 1),
                     labels = c("No", "Yes")) +
  scale_x_continuous(breaks = c(0, 1, 2, 3),
                       labels = c("None", "Little", "Some", "Great extent")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "COVID-19 loneliness", x = "Response", y = "Prooportion (%)", fill = "Chronic condition")
 


A/B/C + plot_annotation(tag_levels = "A") +
  plot_layout(guides = 'collect')
```

## Within-group comparisons over time, adjusted for age & sex & mental health diagnosis (anxiety or depression)

```{r echo=TRUE, warning=FALSE, message=FALSE}
# leger_chronic <- leger %>%
#   filter(chronic_dummy == 1) %>%
#   dplyr::select(impacvd_sq001, impacvd_sq002, impacvd_sq003, wave) %>%
#   mutate_all(as.factor)
# 
# chisq_test(leger_chronic, impacvd_sq001 ~ wave) #NS
# chisq_test(leger_chronic, impacvd_sq002 ~ wave) #NS
# chisq_test(leger_chronic, impacvd_sq003 ~ wave) #NS
# 
# leger_healthy <- leger %>%
#   filter(chronic_dummy == 0) %>%
#   dplyr::select(impacvd_sq001, impacvd_sq002, impacvd_sq003, wave) %>%
#   mutate_all(as.factor)
# 
# chisq_test(leger_healthy, impacvd_sq001 ~ wave) #Sig
# cramerV(leger_healthy$impacvd_sq001, leger_healthy$wave, bias.correct = TRUE)
# # Cramer V 
# #  0.05298
# 
# chisq_test(leger_healthy, impacvd_sq002 ~ wave) #sig
# cramerV(leger_healthy$impacvd_sq002, leger_healthy$wave, bias.correct = TRUE)
# # Cramer V 
# #  0.04708 
#  
# chisq_test(leger_healthy, impacvd_sq003 ~ wave) #sig
# cramerV(leger_healthy$impacvd_sq003, leger_healthy$wave, bias.correct = TRUE)
# # Cramer V 
# #  0.060

```

## Univariate BINARY LOG REGRESSION - CHRONIC
```{r echo=FALSE, warning=FALSE}
leger_model_chronic <- leger %>%
  filter(chronic_dummy == 1) %>%
  dplyr::select(sex, age_yrs, edu, hoinc, chronic_multi, any_m_health, impacvd_sq001, impacvd_sq002, impacvd_sq003) %>%
  mutate_at(vars(impacvd_sq001, impacvd_sq002, impacvd_sq003), ~ifelse(. == 3, 1, 0))

# LOGIT FOR ANXIETY 2 - Impact on my health, including dying
logit_c1 <- glm(impacvd_sq001 ~ sex,
                family = "binomial",
                data = leger_model_chronic)

logit_c2 <- glm(impacvd_sq001 ~ age_yrs,
                family = "binomial",
                data = leger_model_chronic)

logit_c3 <- glm(impacvd_sq001 ~ edu,
                family = "binomial",
                data = leger_model_chronic)

logit_c4 <- glm(impacvd_sq001 ~ hoinc,
                family = "binomial",
                data = leger_model_chronic)

logit_c5 <- glm(impacvd_sq001 ~ chronic_multi,
                family = "binomial",
                data = leger_model_chronic)

logit_c6 <- glm(impacvd_sq001 ~ any_m_health,
                family = "binomial",
                data = leger_model_chronic)

tab_model(logit_c1, logit_c2, logit_c3, logit_c4, logit_c5, logit_c6)

# LOGIT FOR DEPRESSION 2 - Impact on my health, including dying
logit_c1.2 <- glm(impacvd_sq002 ~ sex,
                family = "binomial",
                data = leger_model_chronic)

logit_c2.2 <- glm(impacvd_sq002 ~ age_yrs,
                family = "binomial",
                data = leger_model_chronic)

logit_c3.2 <- glm(impacvd_sq002 ~ edu,
                family = "binomial",
                data = leger_model_chronic)

logit_c4.2 <- glm(impacvd_sq002 ~ hoinc,
                family = "binomial",
                data = leger_model_chronic)

logit_c5.2 <- glm(impacvd_sq002 ~ chronic_multi,
                family = "binomial",
                data = leger_model_chronic)

logit_c6.2 <- glm(impacvd_sq002 ~ any_m_health,
                family = "binomial",
                data = leger_model_chronic)

tab_model(logit_c1.2, logit_c2.2, logit_c3.2, logit_c4.2, logit_c5.2, logit_c6.2)

# LOGIT FOR LONELINESS 2 - Impact on my health, including dying
logit_c1.3 <- glm(impacvd_sq003 ~ sex,
                family = "binomial",
                data = leger_model_chronic)

logit_c2.3 <- glm(impacvd_sq003 ~ age_yrs,
                family = "binomial",
                data = leger_model_chronic)

logit_c3.3 <- glm(impacvd_sq003 ~ edu,
                family = "binomial",
                data = leger_model_chronic)

logit_c4.3 <- glm(impacvd_sq003 ~ hoinc,
                family = "binomial",
                data = leger_model_chronic)

logit_c5.3 <- glm(impacvd_sq003 ~ chronic_multi,
                family = "binomial",
                data = leger_model_chronic)

logit_c6.3 <- glm(impacvd_sq003 ~ any_m_health,
                family = "binomial",
                data = leger_model_chronic)

tab_model(logit_c1.3, logit_c2.3, logit_c3.3, logit_c4.3, logit_c5.3, logit_c6.3)
```

## Univariate BINARY LOG REGRESSION - HEALTHY
```{r echo=FALSE, warning=FALSE}
leger_model_healthy <- leger %>%
  filter(chronic_dummy == 0) %>%
  dplyr::select(sex, age_yrs, edu, hoinc, chronic_multi, any_m_health, impacvd_sq001, impacvd_sq002, impacvd_sq003) %>%
  mutate_at(vars(impacvd_sq001, impacvd_sq002, impacvd_sq003), ~ifelse(. == 3, 1, 0))

# LOGIT FOR ANXIETY 2 - Impact on my health, including dying
logit_h1 <- glm(impacvd_sq001 ~ sex,
                family = "binomial",
                data = leger_model_healthy)

logit_h2 <- glm(impacvd_sq001 ~ age_yrs,
                family = "binomial",
                data = leger_model_healthy)

logit_h3 <- glm(impacvd_sq001 ~ edu,
                family = "binomial",
                data = leger_model_healthy)

logit_h4 <- glm(impacvd_sq001 ~ hoinc,
                family = "binomial",
                data = leger_model_healthy)

logit_h5 <- glm(impacvd_sq001 ~ chronic_multi,
                family = "binomial",
                data = leger_model_healthy)

logit_h6 <- glm(impacvd_sq001 ~ any_m_health,
                family = "binomial",
                data = leger_model_healthy)

tab_model(logit_h1, logit_h2, logit_h3, logit_h4, logit_h5, logit_h6)

# LOGIT FOR DEPRESSION 2 - Impact on my health, including dying
logit_h1.2 <- glm(impacvd_sq002 ~ sex,
                family = "binomial",
                data = leger_model_healthy)

logit_h2.2 <- glm(impacvd_sq002 ~ age_yrs,
                family = "binomial",
                data = leger_model_healthy)

logit_h3.2 <- glm(impacvd_sq002 ~ edu,
                family = "binomial",
                data = leger_model_healthy)

logit_h4.2 <- glm(impacvd_sq002 ~ hoinc,
                family = "binomial",
                data = leger_model_healthy)

logit_h5.2 <- glm(impacvd_sq002 ~ chronic_multi,
                family = "binomial",
                data = leger_model_healthy)

logit_h6.2 <- glm(impacvd_sq002 ~ any_m_health,
                family = "binomial",
                data = leger_model_healthy)

tab_model(logit_h1.2, logit_h2.2, logit_h3.2, logit_h4.2, logit_h5.2, logit_h6.2)

# LOGIT FOR LONELINESS 2 - Impact on my health, including dying
logit_h1.3 <- glm(impacvd_sq003 ~ sex,
                family = "binomial",
                data = leger_model_healthy)

logit_h2.3 <- glm(impacvd_sq003 ~ age_yrs,
                family = "binomial",
                data = leger_model_healthy)

logit_h3.3 <- glm(impacvd_sq003 ~ edu,
                family = "binomial",
                data = leger_model_healthy)

logit_h4.3 <- glm(impacvd_sq003 ~ hoinc,
                family = "binomial",
                data = leger_model_healthy)

logit_h5.3 <- glm(impacvd_sq003 ~ chronic_multi,
                family = "binomial",
                data = leger_model_healthy)

logit_h6.3 <- glm(impacvd_sq003 ~ any_m_health,
                family = "binomial",
                data = leger_model_healthy)

tab_model(logit_h1.3, logit_h2.3, logit_h3.3, logit_h4.3, logit_h5.3, logit_h6.3)
```


### CHI SQUARE AT EACH TIME POINT
#### Wave 2
```{r echo=T}
library(tidymodels)

w2 <- leger %>%
  dplyr::select(impacvd_sq001, impacvd_sq002, impacvd_sq003, chronic_dummy, wave) %>%
  mutate_all(as.factor) %>%
  filter(wave == 2) %>%
  drop_na()

chisq_test(w2, impacvd_sq001 ~ chronic_dummy) #sig
cramerV(w2$impacvd_sq001, w2$chronic_dummy, bias.correct = TRUE)
# Cramer V 
#   0.1334 

chisq_test(w2, impacvd_sq002 ~ chronic_dummy) #sig
cramerV(w2$impacvd_sq002, w2$chronic_dummy, bias.correct = TRUE)
# Cramer V 
#   0.107

chisq_test(w2, impacvd_sq003 ~ chronic_dummy) #sig
cramerV(w2$impacvd_sq003, w2$chronic_dummy, bias.correct = TRUE)
# Cramer V 
#   0.1801  ## biggest effect size - medium

```

#### Wave 3
```{r echo=T}
w3 <- leger %>%
  dplyr::select(impacvd_sq001, impacvd_sq002, impacvd_sq003, chronic_dummy, wave) %>%
  mutate_all(as.factor) %>%
  filter(wave == 3) %>%
  drop_na()

chisq_test(w3, impacvd_sq001 ~ chronic_dummy) #sig.
cramerV(w3$impacvd_sq001, w3$chronic_dummy, bias.correct = TRUE)
# Cramer V 
#  0.09307 
 
chisq_test(w3, impacvd_sq002 ~ chronic_dummy) #NS
chisq_test(w3, impacvd_sq003 ~ chronic_dummy) #NS

```
#### Wave 4
```{r echo=T}
w4 <- leger %>%
  dplyr::select(impacvd_sq001, impacvd_sq002, impacvd_sq003, chronic_dummy, wave) %>%
  mutate_all(as.factor) %>%
  filter(wave == 4) %>%
  drop_na()

chisq_test(w4, impacvd_sq001 ~ chronic_dummy) #sig.
cramerV(w4$impacvd_sq001, w4$chronic_dummy, bias.correct = TRUE)
# Cramer V 
#   0.1055 

chisq_test(w4, impacvd_sq002 ~ chronic_dummy) #sig.
cramerV(w4$impacvd_sq002, w4$chronic_dummy, bias.correct = TRUE)
# Cramer V 
#    0.097 

chisq_test(w4, impacvd_sq003 ~ chronic_dummy) #NS
```

#### Wave 5
```{r echo=T}
w5 <- leger %>%
  dplyr::select(impacvd_sq001, impacvd_sq002, impacvd_sq003, chronic_dummy, wave) %>%
  mutate_all(as.factor) %>%
  filter(wave == 5) %>%
  drop_na()

chisq_test(w5, impacvd_sq001 ~ chronic_dummy) #sig.
cramerV(w5$impacvd_sq001, w5$chronic_dummy, bias.correct = TRUE)
# Cramer V 
#    0.075 

chisq_test(w5, impacvd_sq002 ~ chronic_dummy) #NS

chisq_test(w5, impacvd_sq003 ~ chronic_dummy) #Sig
cramerV(w5$impacvd_sq003, w5$chronic_dummy, bias.correct = TRUE)
# Cramer V 
#  0.07809
```
#### Wave 6
```{r echo=T}
w6 <- leger %>%
  dplyr::select(impacvd_sq001, impacvd_sq002, impacvd_sq003, chronic_dummy, wave) %>%
  mutate_all(as.factor) %>%
  filter(wave == 6) %>%
  drop_na()

chisq_test(w6, impacvd_sq001 ~ chronic_dummy) #sig.
cramerV(w6$impacvd_sq001, w6$chronic_dummy, bias.correct = TRUE)
# Cramer V 
#   0.1142 

chisq_test(w6, impacvd_sq002 ~ chronic_dummy) #sig.
cramerV(w6$impacvd_sq002, w6$chronic_dummy, bias.correct = TRUE)
# Cramer V 
#   0.1294 
  
chisq_test(w6, impacvd_sq003 ~ chronic_dummy) #sig. 
cramerV(w6$impacvd_sq003, w6$chronic_dummy, bias.correct = TRUE)
# Cramer V 
#   0.1271 
```
#### Wave 7
```{r echo=T}
w7 <- leger %>%
  dplyr::select(impacvd_sq001, impacvd_sq002, impacvd_sq003, chronic_dummy, wave) %>%
  mutate_all(as.factor) %>%
  filter(wave == 7) %>%
  drop_na()

chisq_test(w7, impacvd_sq001 ~ chronic_dummy) #sig.
cramerV(w7$impacvd_sq001, w7$chronic_dummy, bias.correct = TRUE)
# Cramer V 
#   0.1269 

chisq_test(w7, impacvd_sq002 ~ chronic_dummy) #sig.
cramerV(w7$impacvd_sq002, w7$chronic_dummy, bias.correct = TRUE)
# Cramer V 
#   0.1103 

chisq_test(w7, impacvd_sq003 ~ chronic_dummy) #NS
```
#### Wave 8
```{r echo=T}
w8 <- leger %>%
  dplyr::select(impacvd_sq001, impacvd_sq002, impacvd_sq003, chronic_dummy, wave) %>%
  mutate_all(as.factor) %>%
  filter(wave == 8) %>%
  drop_na()

chisq_test(w8, impacvd_sq001 ~ chronic_dummy) #sig.
cramerV(w8$impacvd_sq001, w8$chronic_dummy, bias.correct = TRUE)
# Cramer V 
#  0.09665 

chisq_test(w8, impacvd_sq002 ~ chronic_dummy) #sig.
cramerV(w8$impacvd_sq002, w8$chronic_dummy, bias.correct = TRUE)
# Cramer V 
#   0.1109 

chisq_test(w8, impacvd_sq003 ~ chronic_dummy) #sig
cramerV(w8$impacvd_sq003, w8$chronic_dummy, bias.correct = TRUE)
# Cramer V 
#  0.07921 

```
