---
title: "Psychological distress during COVID-19 in Canadian youth with and without chronic health conditions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load the libraries
library(tidyverse)
library(readr)
library(here)
library(english)
library(stringr)
library(scales)
library(ggridges)
library(plotly)
library(patchwork)
library(haven)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# set seed for all analyses and wrangling
 set.seed(1)

## This file is to wrangle Oxford policy data
# Downloaded raw files from GitHub on December 3, 2021
# https://github.com/OxCGRT/covid-policy-tracker/tree/master/data

# # I wanted to get the indices from Canada
# stringency_index_raw <- read_csv("data/stringency_index-jan2022.csv") %>%
#   filter(country_code == "CAN") %>%
#   dplyr::select(-country_code, -country_name, -...1) %>%
#   pivot_longer(cols = everything(), names_to = "date", values_to = "rating")
# 
# write_csv(stringency_index_raw, "Data/stringency_can-jan2022.csv")
# # #
# # # Containment index
# containment_index <- read_csv("data/containment_health_index-jan2022.csv") %>%
#   filter(country_code == "CAN") %>%
#   dplyr::select(-country_code, -country_name, -...1) %>%
#   pivot_longer(cols = everything(), names_to = "date", values_to = "rating")
# 
# write_csv(containment_index, "Data/containment_can-jan2022.csv")

# Because the date was saved as a combination of string and number I manually converted to YYYY-MM-DD format for the ease of processing further
# There is probably a way to do this in r, but I was tired and lazy and it was a quick fix

cases <- read_csv("data/covid19-download-jan2022.csv") %>%
  filter(prname == "Canada") %>%
  dplyr::select(date, avgtotal_last7)
# Read in the data and merge by date
# 
# sting <- read_csv("data/stringency_can-jan2022.csv")
# cont <- read_csv("data/containment_can-jan2022.csv")
# 
# combine <- left_join(sting, cont, by = "date")
# 
# write_csv(combine, "data/combined_oxford-jan2022.csv")

  # rename(c("stingency" = "rating.x", "containment" = "rating.y")) %>%
  # pivot_longer(cols = c(stingency, containment), names_to = "index", values_to = "rating")

# combined_oxford_cases <- left_join(combined_oxford, cases, by = "date") %>%
#   filter(date > "2020-06-01") %>% 
#   filter(date < "2021-09-30") %>%
#   rename(c("stingency" = "rating.x", "containment" = "rating.y")) %>%
#   pivot_longer(cols = c(stingency, containment, numtoday), names_to = "index", values_to = "rating")
#   
combined_oxford <- read_csv("data/combined_oxford-jan2022.csv")

test <- left_join(combined_oxford, cases, by = "date") %>%
  filter(date > "2020-06-01") %>% 
  filter(date < "2021-12-05") %>%
  rename(c("stingency" = "rating.x", "containment" = "rating.y")) %>%
  pivot_longer(cols = c(stingency, containment), names_to = "index", values_to = "rating") %>%
  mutate(group = as.factor(case_when(
    date > "2020-06-02" & date < "2020-06-13" ~ 1,
    date > "2020-10-27" & date < "2020-11-11" ~ 2,
    date > "2021-01-26" & date < "2021-02-08" ~ 3,
    date > "2021-03-10" & date < "2021-03-24" ~ 4,
    date > "2021-05-30" & date < "2021-06-15" ~ 5,
    date > "2021-09-09" & date < "2021-09-21" ~ 6,
    date > "2021-11-15" & date < "2021-12-03" ~ 7)))# added the latest wave
###
coeff <- 130

ggplot(test, aes(x=date)) +
  geom_line(aes(y = avgtotal_last7/coeff), color = "light blue", size = 1) + # Divide by 10 to get the same range than the temperature
    #geom_ribbon(aes(x = date, group = group, ymax = avgtotal_last7, ymin = 0), fill = "light blue", alpha = 0.3) +
  geom_line(aes(y = rating, color = index), size = 1) +
  scale_y_continuous(name = "Stingency and containment indices",
                     sec.axis = sec_axis(~.*coeff, name="7-day avg COVID-19 cases"))+
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank()) +
  scale_x_date(date_labels = "%b %d", date_breaks = "1 month") +
  geom_ribbon(aes(x = date, group = group, ymax = avgtotal_last7/coeff, ymin = 0), fill = "blue", alpha = 0.4) +
  labs(x = "Time", color = "Oxford Index")
```
