---
title: "Project log"
author: "Prepared by UK"
date: "First opened: 2021-11-17 | Last update: `r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***

I re-started the project log recently with the updates and changes for an article titled: *Psychological distress during COVID-19 in Canadian young adults with and without chronic health conditions*. This is to assure for transparency of the work. Because this work was pushed aside for a while, some of the reporting of the process is retrospective. 

*** 

###  Retrospective report:
**March 2021**

Project began on *March 15, 2021*. The original proposal for secondary data analyses was registered and can be viewed at [ISAP log - iCARE-UK-0026](https://mbmc-cmcm.ca/covid19/apl/log/).

**April 2021**
Draft of the article circulated among some team members. Received feedback from SB, JS. Project stalled due to internal processes and shift in priorities.

**October 2021**
The latest Canadian representative data is added, cleaned and ready for analyses.

Changes & deliberations:

* The number of cancer cases in young people is too low to separate, chronic health conditions will be collapsed into a single group and compared to healthy people with no physical chronic health conditions
* The focus is shifted entirely on the psychological distress in order to keep the focus narrower, health concerns are to be considered in a separate project
* Wave 1 is excluded because the data on psychological distress has only been collected in wave 2 and onward
* Psychological distress is treated as a compound score of 4 items, see CFA analyses for details. The main outcome of interest is thus COVID-19 psychological distress and is now treated as a continuous variable.

***
####  Prospective reporting:

**Wednesday, November 17, 2021**
Met KJD, TBP in order to discuss the findings (visual data exploration). We discussed the possibility of adding the health behaviours during the pandemic such as changes in using alcohol, smoking, vaping and recreational drugs.

Suggestion was made to perform some sort of sub-analyses by chronic health condition group (although numbers are smaller, statistical power lower)

**Friday, Nov. 19, 2021**

Met with SB to discuss the visual exploration of the data, the same I presented and discussed with KJD and TBP. We decided to structure the narrative around the relative distress levels over time in the 2 different groups: chronic health and healthy people.

The health behaviors (i.e. alcohol/drug use) is discussed. We decided to keep this for a second paper where we can look at "coping mechanisms" i.e. drug use, and how that relates to distress.

The following will be done:
Focus of the analyses remains around the psychological distress over waves of the surveys. The focus is structured around any differences that occur in individuals with and without chronic health conditions

**Analyses to do**:

* The data was collected over several months which also corresponds to different periods within the pandemic. We will incorporate the data of cases in Canada over time, and include over which periods the data was collected.

* Psychological distress is known to vary between sex, so I will separate analyses by sex: female vs male

* **Distress over time**: ANOVA or non-parametric equivalent will be used to evaluate mean differences of psychological distress across different survey waves in 4 groups: females with & without chronic health conditions and males with and without chronic health conditions. Posthoc analyses will reveal where any significant discrepancies over time occur.

* **Distress within survey wave**: The aim is to compare the distress between individuals with and without chronic health conditions across each survey wave and within sex. Individual t tests or non-parametric equivalent will be used to evaluate at which points in the pandemic (if any) significant differences in levels of distress occur among groups.

Covariates to consider:

* *age*
* *hoinc* = perceived income, as a proxy for socio-economic status

--> These could be considered in sensitivity analyses. 

**Tuesday, Nov. 23, 2021**

Back to some data-pre-processing - recoded the distress sum so that each item is reverse coded instead of the sum. Nothing in the output changes, it is just a personal preference as it is more intuitive to read lower numbers as lower distress/extent.

**Wednesday, Nov. 24, 2021**

Evaluated feasibility of running ANOVAs by checking the assumptions. In some cases robust models will be necessary. 

Started working on the analyses within groups over time.

**Wednesday, Dec. 1, 2021**

Met with TBP and KJD to discuss the output of ANCOVAs Plotted covid cases in canada and aligned the plot with the surveys.
Getting ready to write up the manuscrupt. Need to prepare the figures, I think I will add marginal means with se for the trend and the boxplot broken down by sex.

Data for the cases plot was extracted on December 1, 2021 from the [government's website](https://health-infobase.canada.ca/covid-19/epidemiological-summary-covid-19-cases.html?stat=num&measure=active&map=pt#a2).

Extracted marginal means and CIs from the models in order to plot the trend of the distress over time.

**Friday, Dec 3, 2021**
[Retrospective entry] Downloaded Oxford Policy Data from GitHub. Cleaned and prepared for the plot.
[Click here](https://www.bsg.ox.ac.uk/research/research-projects/covid-19-government-response-tracker) to read more. I focused exclusively on stringency and containment indices for Canada as a whole.

**Wednesday, Dec 8, 2021**

Wrote introduction and 90% of the method section. Re-ran the scripts and separated them, started organizing for publication.